openapi: 3.0.2
info:
  title: Scraper API
  contact:
    name: Graham Guthrie
    email: bcanvas1ad@gmail.com
  version: "1.0"
servers:
- url: http://localhost/api/v1
tags:
- name: DFS Scraper API
  description: Scrape daily fantasy sports data from provider sites
paths:
  /getSupportedProviders:
    get:
      tags:
      - DFS Scraper API
      summary: Get list of supported data providers
      description: Get list of supported daily fantasy data providers
      operationId: get_supported_providers
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                x-content-type: application/json
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      x-openapi-router-controller: swagger_server.controllers.dfs_scraper_api_controller
  /getSupportedPlatforms:
    get:
      tags:
      - DFS Scraper API
      summary: Get list of supported contest platforms
      description: Get list of supported daily fantasy contest platforms
      operationId: get_supported_platforms
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                x-content-type: application/json
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      x-openapi-router-controller: swagger_server.controllers.dfs_scraper_api_controller
  /getSupportedSports:
    get:
      tags:
      - DFS Scraper API
      summary: Get list of supported sports
      description: Get list of supported sport codes
      operationId: get_supported_sports
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  maxLength: 3
                  minLength: 3
                  type: string
                x-content-type: application/json
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      x-openapi-router-controller: swagger_server.controllers.dfs_scraper_api_controller
  /getDate:
    get:
      tags:
      - DFS Scraper API
      summary: Get contest date
      description: Get contest date
      operationId: get_date
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
                description: Date
                format: YYYY-MM-DD
                example: 2021-06-03T00:00:00.000Z
                x-content-type: application/json
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      x-openapi-router-controller: swagger_server.controllers.dfs_scraper_api_controller
  /getPlayerList/{provider}/{platform}/{sport}/{_date}:
    get:
      tags:
      - DFS Scraper API
      summary: "Get list of daily fantasy players for a specified sport, platform\
        \ and slate"
      description: Get list of valid players
      operationId: get_player_list
      parameters:
      - name: provider
        in: path
        description: Daily fatansy sports data provider
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: DailyFantasyFuel
      - name: platform
        in: path
        description: Daily fatansy sports contest website
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: Draftkings or Fanduel
      - name: sport
        in: path
        description: Supported sport
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: NBA or MLB
      - name: _date
        in: path
        description: Date
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: YYYY-MM-DD
        example: 2021-06-03
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerList'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      x-openapi-router-controller: swagger_server.controllers.dfs_scraper_api_controller
components:
  schemas:
    Player:
      type: object
      properties:
        id:
          type: integer
          description: Player Id
          example: 1
        date:
          type: string
          description: Date
          format: YYYY-MM-DD
          example: 2021-06-03T00:00:00.000Z
        name:
          type: string
          description: Player Name
          example: Lebron James
        fn:
          type: string
          description: Player First Name
          example: Lebron
        ln:
          type: string
          description: Player Last Name
          example: James
        pos:
          type: string
          description: Position
          example: C
        inj:
          type: string
          description: Injury Status
          example: O
        team:
          type: string
          description: Team
          example: LAL
        salary:
          type: integer
          description: Salary
          example: 7000
        ppg_proj:
          type: number
          description: Projected fantasy points
          format: float
          example: 56.26
        value_proj:
          type: number
          description: Projected fantasy value
          format: float
          example: 4.25
      description: Player schema
      example:
        date: 2021-06-03T00:00:00.000Z
        ln: James
        value_proj: 4.25
        inj: O
        pos: C
        ppg_proj: 56.26
        name: Lebron James
        fn: Lebron
        id: 1
        team: LAL
        salary: 7000
    PlayerList:
      type: array
      description: List of players
      items:
        $ref: '#/components/schemas/Player'

